#!/usr/bin/env bash

stdin=$(cat)

script_dir=$(dirname "$0")
. $script_dir/tunnel.sh

dst_host=$(get_host_ip $2)
src_host=$(get_host_ip $3)

###############################

open_tunnel "$dst_host" "${TUNNEL_IPS[0]}"
ssh "$dst_host" ". $script_dir/tunnel.sh; open_tunnel $src_host ${TUNNEL_IPS[1]}"

# Run original migrate
echo "$stdin" | "${script_dir}/migrate_default" "$1" "${TUNNEL_IPS[1]}" "$3" "$4" "$5"

close_tunnel
ssh "$dst_host" ". $script_dir/tunnel.sh; close_tunnel"

